app:
  name: "FitMachine API"
  version: "1.0.0"
  port: "8080"
  env: "local"

database:
  host: "localhost"
  port: "5432"
  user: "fitmachine"
  password: "fitmachine"
  dbname: "fitmachine"
  sslmode: "disable"

server:
  host: "localhost"
  port: "8080"
  read_timeout: !!duration 30s
  write_timeout: !!duration 30s
  cors:
    allowed_origins: ["http://localhost:3000", "http://localhost:3001"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["Content-Type", "Authorization"]

log:
  level: "debug"
  format: "text"
