// Code generated by scratch; DO NOT EDIT.
// Package config содержит структуры конфигурации приложения
package config

const (
	// App конфигурация приложения
	AppName    = "app.name"
	AppVersion = "app.version"
	AppPort    = "app.port"
	AppEnv     = "app.env"

	// Database конфигурация базы данных
	DatabaseHost     = "database.host"
	DatabasePort     = "database.port"
	DatabaseUser     = "database.user"
	DatabasePassword = "database.password"
	DatabaseDBName   = "database.dbname"
	DatabaseSSLMode  = "database.sslmode"

	// Server конфигурация HTTP сервера
	ServerHost         = "server.host"
	ServerPort         = "server.port"
	ServerReadTimeout  = "server.read_timeout"
	ServerWriteTimeout = "server.write_timeout"

	// CORS конфигурация
	CORSAllowedOrigins = "server.cors.allowed_origins"
	CORSAllowedMethods = "server.cors.allowed_methods"
	CORSAllowedHeaders = "server.cors.allowed_headers"

	// Log конфигурация логирования
	LogLevel  = "log.level"
	LogFormat = "log.format"
)
